"""Conversational mode: hand the inventory to the user's local Claude Code CLI.

PartsMatcher deliberately does NOT call the Anthropic API and needs no API
key. Instead it prepares a session workspace — a generated CLAUDE.md carrying
the parts inventory, the deterministic match report, and workbench-assistant
guidance, alongside copies of the raw JSON — and launches the `claude` binary
the user already has installed and logged in. Claude Code reads CLAUDE.md at
session start, so the chat opens already knowing exactly what the user owns,
and their existing subscription auth applies.

The deterministic matcher (`partsmatcher match`) stays fully offline and
never requires Claude to be installed.
"""

from __future__ import annotations

import json
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path
from typing import Callable, Optional, Sequence

from .matcher import Inventory, MatchReport, PartsMatcherError, parse_inventory

CONTEXT_MARKER = "<!-- Generated by PartsMatcher chat"

ALIAS_FILENAME = "aliases.jsonl"

CLAUDE_NOT_FOUND_HINT = """\
partsmatcher: error: could not find {binary!r} on PATH.

PartsMatcher chat drives your locally installed Claude Code CLI as a child
process (your existing subscription login — no API key, no per-token billing
from this tool). Install it first:

    npm install -g @anthropic-ai/claude-code

or see https://code.claude.com/docs for other installers, then run `claude`
once to log in. The deterministic matcher works without it:

    python -m partsmatcher match
"""


def find_claude(
    binary: str = "claude",
    which: "Callable[[str], Optional[str]]" = shutil.which,
) -> "Optional[str]":
    """Locate the Claude Code CLI on PATH; None if not installed."""
    return which(binary)


def _render_report_section(report: MatchReport) -> str:
    lines = []
    lines.append(
        "PartsMatcher's deterministic set-cover matcher compared this inventory "
        "against the project database in `projects.json` (a project short a "
        f"total of {report.almost_threshold} parts or fewer counts as ALMOST "
        "THERE). Build on this — don't recompute it:"
    )
    lines.append("")
    build_now = ", ".join(m.name for m in report.build_now) or "(none)"
    lines.append(f"BUILD NOW ({len(report.build_now)}): {build_now}")
    lines.append(f"ALMOST THERE ({len(report.almost)}), fewest missing first:")
    if not report.almost:
        lines.append("  (none)")
    for result in report.almost:
        parts = ", ".join(
            f"{p.name} (have {p.have} of {p.required})" for p in result.missing
        )
        lines.append(f"  - {result.name}: short {result.total_missing} — {parts}")
    lines.append(f"NOT YET ({len(report.not_yet)}):")
    if not report.not_yet:
        lines.append("  (none)")
    for result in report.not_yet:
        parts = ", ".join(
            f"{p.name} (have {p.have} of {p.required})" for p in result.missing
        )
        lines.append(
            f"  - {result.name}: short {result.total_missing} across "
            f"{result.missing_kinds} part types — {parts}"
        )
    return "\n".join(lines)


def build_context_markdown(
    inventory: Inventory, report: "Optional[MatchReport]"
) -> str:
    """Render the CLAUDE.md that seeds the Claude Code session with context."""
    lines = [
        f"{CONTEXT_MARKER}. Safe to delete; regenerated on each chat session. -->",
        "",
        "# PartsMatcher workbench session",
        "",
        "You are helping a hobbyist decide what to build with the electronics",
        "parts they actually own, explain wiring, and adapt when parts are",
        "missing. This folder is a PartsMatcher chat workspace.",
        "",
        "## Parts inventory — the source of truth",
        "",
        "The user owns exactly these parts and nothing more. The raw data is in",
        "`inventory.json` (same schema the deterministic matcher reads).",
        "",
    ]
    for key, display in inventory.display_names.items():
        lines.append(f"- {display} ×{inventory.quantities[key]}")
    lines.append("")
    lines.append(
        f"({inventory.distinct_parts} part types, {inventory.total_units} parts total)"
    )
    lines.append("")
    lines.append("## Deterministic match report")
    lines.append("")
    if report is not None:
        lines.append(_render_report_section(report))
    else:
        lines.append(
            "No project database was loaded for this session — improvise "
            "project ideas directly from the inventory above."
        )
    lines += [
        "",
        "## How to help",
        "",
        "- Treat the inventory as exact, and count quantities: a project that",
        "  needs 3 LEDs when the user owns 2 is short 1 LED — say so explicitly.",
        "- Improvise project ideas beyond the database freely, but ground every",
        "  suggestion in parts on hand. Clearly flag anything that must be",
        "  bought, and prefer ideas that need nothing extra.",
        "- If the user says a part is missing, broken, or tied up in another",
        "  build, adapt: suggest substitutes from the inventory and explain the",
        "  tradeoffs (e.g. a transistor standing in for a relay).",
        "- Wiring help: breadboard-level and pin by pin, with resistor values",
        "  and which rail goes where. Assume a curious beginner unless they",
        "  show otherwise.",
        "- Mention safety only where it genuinely matters (mains voltage, LiPo",
        "  charging, stalled motors).",
        "- The user can re-run `python -m partsmatcher match` anytime for a",
        "  fresh deterministic report against the current `inventory.json`.",
        "",
        "## Inventory intake — adding parts conversationally",
        "",
        "When the user describes parts in plain language (\"I picked up a strip",
        "of neopixels\", \"add two more nanos\", \"used up four of the red LEDs\"),",
        "run intake:",
        "",
        "1. Normalize each described part against the inventory:",
        "   - If it is a part already in the inventory under different wording,",
        "     reuse the existing canonical name exactly (\"nano\" → \"Arduino",
        "     Nano\").",
        "   - Otherwise mint a clear canonical name — specific enough to shop",
        "     by, with the defining spec in the name (value, size, color: e.g.",
        "     \"470 ohm resistor\", \"WS2812B LED strip (1 m)\").",
        "2. Ask a clarifying question whenever an entry is ambiguous instead of",
        "   guessing: vague quantity (\"a handful\"), missing spec (\"some",
        "   resistors\" — what value?), ambiguous identity (\"an arduino\" — which",
        "   board?), or unclear overlap with an existing entry.",
        "3. Confirm the batch before writing: show one line per part,",
        "   `raw phrasing → Canonical Name ×qty`, and get a yes.",
        "4. Update `inventory.json` in this folder, keeping the schema:",
        "   `{\"parts\": [{\"name\": str, \"quantity\": int >= 0}, ...]}`. Merge into",
        "   an existing entry (sum quantities) rather than appending a",
        "   duplicate name; preserve extra fields on existing entries; for",
        "   parts the user reports using up, decrement (floor at 0).",
        "5. Append one JSON line to `aliases.jsonl` for every normalized entry",
        "   — this grows the naming-alias dataset for a future vision module:",
        "",
        '   {"raw": "<user\'s exact phrasing for that part>", "name": "<canonical name>", "quantity": <n>, "action": "added|merged|used|corrected|reference"}',
        "",
        "   - Log corrections too: if the user corrects your normalization,",
        "     append a new record with action \"corrected\" for the fixed",
        "     mapping — corrections are the most valuable alias data.",
        "   - If the user refers to an existing part by another name in",
        "     passing (\"the sonar sensor\" for the HC-SR04), append a record",
        "     with action \"reference\".",
        "   - `aliases.jsonl` is append-only: never rewrite, reorder, or",
        "     delete existing lines.",
        "",
        "When the session ends, PartsMatcher validates the updated",
        "`inventory.json` and syncs it — plus any new alias records — back to",
        "the user's own files, so keep both files valid at all times.",
        "",
    ]
    return "\n".join(lines)


def prepare_workspace(
    workdir: "Optional[str]",
    context_markdown: str,
    data_files: "dict[str, str]",
) -> Path:
    """Create (or reuse) the session directory and write CLAUDE.md + data files.

    A CLAUDE.md not generated by PartsMatcher is never overwritten — that
    would clobber a file the user owns.
    """
    if workdir is None:
        base = Path(tempfile.mkdtemp(prefix="partsmatcher-chat-"))
    else:
        base = Path(workdir).expanduser().resolve()
        base.mkdir(parents=True, exist_ok=True)
    claude_md = base / "CLAUDE.md"
    if claude_md.exists():
        existing = claude_md.read_text(encoding="utf-8")
        if CONTEXT_MARKER not in existing:
            raise PartsMatcherError(
                f"refusing to overwrite {claude_md} — it was not generated by "
                "PartsMatcher; pick a different --workdir"
            )
    claude_md.write_text(context_markdown, encoding="utf-8")
    for name, text in data_files.items():
        (base / name).write_text(text, encoding="utf-8")
    return base


def _count_records(text: str) -> int:
    return len([line for line in text.splitlines() if line.strip()])


def _sync_inventory(
    workspace: Path,
    *,
    original_inventory_text: str,
    inventory_store: "Optional[Path]",
) -> "list[str]":
    """Flow a changed workspace inventory back to the user's own file."""
    inventory_path = workspace / "inventory.json"
    try:
        updated = inventory_path.read_text(encoding="utf-8")
    except OSError:
        return [
            f"warning: {inventory_path} is missing; your inventory file was "
            "left untouched"
        ]
    if updated == original_inventory_text:
        return []
    try:
        new_inventory = parse_inventory(json.loads(updated))
    except (json.JSONDecodeError, PartsMatcherError) as exc:
        return [
            f"warning: the session changed inventory.json but it no longer "
            f"validates ({exc}); your inventory file was left untouched — "
            f"the edited copy is at {inventory_path}"
        ]
    old_inventory = parse_inventory(json.loads(original_inventory_text))
    delta = (
        f"{old_inventory.distinct_parts} → {new_inventory.distinct_parts} part "
        f"types, {old_inventory.total_units} → {new_inventory.total_units} parts"
    )
    if inventory_store is None:
        return [
            f"inventory changed during the session ({delta}). You were using "
            f"the bundled sample, so nothing was overwritten — the updated "
            f"file is at {inventory_path}; pass your own inventory path to "
            "persist changes automatically."
        ]
    backup = inventory_store.with_name(inventory_store.name + ".bak")
    try:
        backup.write_text(
            inventory_store.read_text(encoding="utf-8"), encoding="utf-8"
        )
        inventory_store.write_text(updated, encoding="utf-8")
    except OSError as exc:
        return [
            f"warning: could not update {inventory_store} ({exc}); the edited "
            f"copy is at {inventory_path}"
        ]
    return [
        f"inventory updated: {inventory_store} ({delta}; previous version "
        f"saved to {backup.name})"
    ]


def _sync_aliases(
    workspace: Path,
    *,
    alias_seed_count: int,
    alias_store: "Optional[Path]",
) -> "list[str]":
    """Append alias records added this session to the persistent dataset."""
    alias_path = workspace / ALIAS_FILENAME
    try:
        alias_text = alias_path.read_text(encoding="utf-8")
    except OSError:
        return []
    lines = [line for line in alias_text.splitlines() if line.strip()]
    new_lines = lines[alias_seed_count:]
    valid, skipped = [], 0
    for line in new_lines:
        try:
            record = json.loads(line)
        except json.JSONDecodeError:
            skipped += 1
            continue
        if isinstance(record, dict) and record.get("raw") and record.get("name"):
            valid.append(line)
        else:
            skipped += 1
    messages = []
    if skipped:
        messages.append(
            f"warning: skipped {skipped} malformed alias record(s) in "
            f"{alias_path.name}"
        )
    if not valid:
        return messages
    if alias_store is None:
        messages.append(
            f"{len(valid)} naming-alias record(s) captured at {alias_path} — "
            "pass your own inventory path to grow a persistent alias dataset."
        )
        return messages
    try:
        with open(alias_store, "a", encoding="utf-8") as handle:
            for line in valid:
                handle.write(line + "\n")
    except OSError as exc:
        messages.append(
            f"warning: could not append to {alias_store} ({exc}); new records "
            f"remain at {alias_path}"
        )
        return messages
    messages.append(
        f"{len(valid)} naming-alias record(s) appended to {alias_store} "
        "(dataset for the future vision module)"
    )
    return messages


def run_chat(
    *,
    inventory: Inventory,
    inventory_text: str,
    report: "Optional[MatchReport]" = None,
    projects_text: "Optional[str]" = None,
    inventory_store: "Optional[Path]" = None,
    alias_store: "Optional[Path]" = None,
    alias_seed_text: str = "",
    sync: bool = True,
    workdir: "Optional[str]" = None,
    prompt: "Optional[str]" = None,
    claude_bin: str = "claude",
    claude_args: "Sequence[str]" = (),
    which: "Callable[[str], Optional[str]]" = shutil.which,
    launch: "Callable[..., int]" = subprocess.call,
) -> int:
    """Prepare the workspace, hand the terminal over to Claude Code, sync back.

    `which` and `launch` are injectable so tests never need Claude installed.
    The child inherits this process's stdin/stdout/stderr, so it talks to the
    user's real terminal directly — the full interactive Claude Code UI.

    After the session ends, inventory edits made in the workspace are
    validated and written back to `inventory_store` (with a .bak backup), and
    alias records appended during the session flow into `alias_store`. With a
    `None` store (bundled sample data) nothing outside the workspace is
    touched — the summary says where the files are instead.
    """
    claude_path = find_claude(claude_bin, which=which)
    if claude_path is None:
        print(CLAUDE_NOT_FOUND_HINT.format(binary=claude_bin), file=sys.stderr)
        return 2

    context = build_context_markdown(inventory, report)
    data_files = {"inventory.json": inventory_text, ALIAS_FILENAME: alias_seed_text}
    if projects_text is not None:
        data_files["projects.json"] = projects_text
    workspace = prepare_workspace(workdir, context, data_files)

    print(
        f"PartsMatcher chat — {inventory.distinct_parts} part types "
        f"({inventory.total_units} parts) loaded as context."
    )
    print(f"Session workspace: {workspace}")
    print("  CLAUDE.md — inventory + match report Claude reads at startup")
    print("  " + " / ".join(sorted(data_files)) + " — live data files")
    print(
        "Describe new parts in plain language and Claude will fold them into "
        "inventory.json, logging naming aliases as it goes."
    )
    print(
        "Launching your local Claude Code (`claude`) — existing login, "
        "no API key. Type /exit to come back."
    )
    print()

    command = [claude_path, *claude_args]
    if prompt:
        command.append(prompt)
    try:
        code = launch(command, cwd=str(workspace))
    except KeyboardInterrupt:
        code = 130

    if sync:
        messages = _sync_inventory(
            workspace,
            original_inventory_text=inventory_text,
            inventory_store=inventory_store,
        )
        messages += _sync_aliases(
            workspace,
            alias_seed_count=_count_records(alias_seed_text),
            alias_store=alias_store,
        )
        for message in messages:
            print(message)
    else:
        print(f"(--no-sync: any changes stay in the workspace at {workspace})")
    return code
