"""Conversational mode: hand the inventory to the user's local Claude Code CLI.

PartsMatcher deliberately does NOT call the Anthropic API and needs no API
key. Instead it prepares a session workspace — a generated CLAUDE.md carrying
the parts inventory, the deterministic match report, and workbench-assistant
guidance, alongside copies of the raw JSON — and launches the `claude` binary
the user already has installed and logged in. Claude Code reads CLAUDE.md at
session start, so the chat opens already knowing exactly what the user owns,
and their existing subscription auth applies.

The deterministic matcher (`partsmatcher match`) stays fully offline and
never requires Claude to be installed.
"""

from __future__ import annotations

import json
import shlex
import shutil
import subprocess
import sys
import tempfile
import time
from dataclasses import dataclass, field
from pathlib import Path
from typing import Callable, Optional, Sequence

from .matcher import (
    Inventory,
    MatchReport,
    PartsMatcherError,
    parse_inventory,
    parse_projects,
)

CONTEXT_MARKER = "<!-- Generated by PartsMatcher chat"

ALIAS_FILENAME = "aliases.jsonl"

PHOTO_DIRNAME = "photos"

WORKSPACE_PREFIX = "partsmatcher-chat-"

SESSION_FILENAME = ".partsmatcher-session.json"

# Image types Claude Code's Read tool can render.
IMAGE_SUFFIXES = (".png", ".jpg", ".jpeg", ".gif", ".webp")

DEFAULT_PHOTO_PROMPT = (
    "Start with photo intake: identify the parts in the photos/ directory "
    "and walk me through confirming them into the inventory."
)

# With no user prompt and no photos, the session would open as a blank
# terminal — greet instead, so the user knows what they're looking at.
DEFAULT_KICKOFF_PROMPT = (
    "Briefly introduce this PartsMatcher session from the context you've "
    "read: the inventory size, the match report's headline (or that no "
    "project database is loaded), and the ways you can help — project "
    "ideas and wiring, plain-language inventory intake, photo intake, "
    "project-database intake, reconciliation. Keep it short and end by "
    "asking what the user wants to do."
)

SAMPLE_PROJECTS_PATH = Path(__file__).resolve().parent / "samples" / "projects.json"

CLAUDE_NOT_FOUND_HINT = """\
partsmatcher: error: could not find {binary!r} on PATH.

PartsMatcher chat drives your locally installed Claude Code CLI as a child
process (your existing subscription login — no API key, no per-token billing
from this tool). Install it first:

    npm install -g @anthropic-ai/claude-code

or see https://code.claude.com/docs for other installers, then run `claude`
once to log in. The deterministic matcher works without it:

    python -m partsmatcher match
"""


def find_claude(
    binary: str = "claude",
    which: "Callable[[str], Optional[str]]" = shutil.which,
) -> "Optional[str]":
    """Locate the Claude Code CLI on PATH; None if not installed."""
    return which(binary)


def _render_report_section(report: MatchReport) -> str:
    lines = []
    lines.append(
        "PartsMatcher's deterministic set-cover matcher compared this inventory "
        "against the project database in `projects.json` (a project short a "
        f"total of {report.almost_threshold} parts or fewer counts as ALMOST "
        "THERE). Build on this — don't recompute it:"
    )
    lines.append("")
    build_now = ", ".join(m.name for m in report.build_now) or "(none)"
    lines.append(f"BUILD NOW ({len(report.build_now)}): {build_now}")
    lines.append(f"ALMOST THERE ({len(report.almost)}), fewest missing first:")
    if not report.almost:
        lines.append("  (none)")
    for result in report.almost:
        parts = ", ".join(
            f"{p.name} (have {p.have} of {p.required})" for p in result.missing
        )
        lines.append(f"  - {result.name}: short {result.total_missing} — {parts}")
    lines.append(f"NOT YET ({len(report.not_yet)}):")
    if not report.not_yet:
        lines.append("  (none)")
    for result in report.not_yet:
        parts = ", ".join(
            f"{p.name} (have {p.have} of {p.required})" for p in result.missing
        )
        lines.append(
            f"  - {result.name}: short {result.total_missing} across "
            f"{result.missing_kinds} part types — {parts}"
        )
    return "\n".join(lines)


def build_context_markdown(
    inventory: Inventory,
    report: "Optional[MatchReport]",
    photo_names: "Sequence[str]" = (),
    match_command: "Optional[str]" = None,
    projects_loaded: bool = False,
    projects_store_name: "Optional[str]" = None,
) -> str:
    """Render the CLAUDE.md that seeds the Claude Code session with context."""
    lines = [
        f"{CONTEXT_MARKER}. Safe to delete; regenerated on each chat session. -->",
        "",
        "# PartsMatcher workbench session",
        "",
        "You are helping a hobbyist decide what to build with the electronics",
        "parts they actually own, explain wiring, and adapt when parts are",
        "missing. This folder is a PartsMatcher chat workspace.",
        "",
        "## Parts inventory — the source of truth",
        "",
        "The user owns exactly these parts and nothing more. The raw data is in",
        "`inventory.json` (same schema the deterministic matcher reads).",
        "",
    ]
    for key, display in inventory.display_names.items():
        lines.append(f"- {display} ×{inventory.quantities[key]}")
    lines.append("")
    lines.append(
        f"({inventory.distinct_parts} part types, {inventory.total_units} parts total)"
    )
    lines.append("")
    lines.append("## Deterministic match report")
    lines.append("")
    if report is not None:
        lines.append(_render_report_section(report))
    else:
        lines.append(
            "No project database was loaded for this session — improvise "
            "project ideas directly from the inventory above."
        )
    lines += [
        "",
        "## How to help",
        "",
        "- Treat the inventory as exact, and count quantities: a project that",
        "  needs 3 LEDs when the user owns 2 is short 1 LED — say so explicitly.",
        "- Improvise project ideas beyond the database freely, but ground every",
        "  suggestion in parts on hand. Clearly flag anything that must be",
        "  bought, and prefer ideas that need nothing extra.",
        "- If the user says a part is missing, broken, or tied up in another",
        "  build, adapt: suggest substitutes from the inventory and explain the",
        "  tradeoffs (e.g. a transistor standing in for a relay).",
        "- Wiring help: breadboard-level and pin by pin, with resistor values",
        "  and which rail goes where. Assume a curious beginner unless they",
        "  show otherwise.",
        "- Mention safety only where it genuinely matters (mains voltage, LiPo",
        "  charging, stalled motors).",
        "- Prefer compact lists over wide tables: this renders in a terminal,",
        "  where wide tables wrap into unreadable fragments.",
    ]
    if match_command:
        lines += [
            "- Re-run the deterministic matcher anytime the inventory changes —",
            "  run it yourself from this folder for a fresh report instead of",
            "  recomputing matches by hand:",
            "",
            f"      {match_command}",
        ]
    else:
        lines += [
            "- The user can re-run `python -m partsmatcher match` anytime for a",
            "  fresh deterministic report against the current `inventory.json`.",
        ]
    lines += [
        "",
        "## Inventory intake — adding parts conversationally",
        "",
        "When the user describes parts in plain language (\"I picked up a strip",
        "of neopixels\", \"add two more nanos\", \"used up four of the red LEDs\"),",
        "run intake:",
        "",
        "1. Normalize each described part against the inventory:",
        "   - If it is a part already in the inventory under different wording,",
        "     reuse the existing canonical name exactly (\"nano\" → \"Arduino",
        "     Nano\").",
        "   - When the project database is loaded, prefer ITS part names for",
        "     the same physical part — the deterministic matcher matches names",
        "     exactly, so a project's \"USB cable\" is only satisfied by an",
        "     inventory entry named \"USB cable\", never by \"USB-A to Mini-B",
        "     lead\".",
        "   - Otherwise mint a clear canonical name — specific enough to shop",
        "     by, with the defining spec in the name (value, size, color: e.g.",
        "     \"470 ohm resistor\", \"WS2812B LED strip (1 m)\").",
        "2. Ask a clarifying question whenever an entry is ambiguous instead of",
        "   guessing: vague quantity (\"a handful\"), missing spec (\"some",
        "   resistors\" — what value?), ambiguous identity (\"an arduino\" — which",
        "   board?), or unclear overlap with an existing entry.",
        "3. Confirm the batch before writing: show one line per part,",
        "   `raw phrasing → Canonical Name ×qty`, and get a yes.",
        "4. Update `inventory.json` in this folder, keeping the schema:",
        "   `{\"parts\": [{\"name\": str, \"quantity\": int >= 0}, ...]}`. Merge into",
        "   an existing entry (sum quantities) rather than appending a",
        "   duplicate name; preserve extra fields on existing entries; for",
        "   parts the user reports using up, decrement (floor at 0).",
        "5. Append one JSON line to `aliases.jsonl` for every normalized entry",
        "   — this grows the naming-alias dataset for a future vision module:",
        "",
        '   {"raw": "<user\'s exact phrasing for that part>", "name": "<canonical name>", "quantity": <n>, "action": "added|merged|used|corrected|reference|photo"}',
        "",
        "   - Log corrections too: if the user corrects your normalization,",
        "     append a new record with action \"corrected\" for the fixed",
        "     mapping — corrections are the most valuable alias data.",
        "   - If the user refers to an existing part by another name in",
        "     passing (\"the sonar sensor\" for the HC-SR04), append a record",
        "     with action \"reference\".",
        "   - `aliases.jsonl` is append-only: never rewrite, reorder, or",
        "     delete existing lines.",
        "6. Multi-value assortments (resistor/LED/capacitor kits): a single",
        "   \"kit ×1\" entry cannot satisfy any project requirement, so offer",
        "   to expand the kit into the specific values the user actually has",
        "   or the projects call for (\"220 ohm resistor ×20\", \"10k ohm",
        "   resistor ×20\") — ask which values and roughly how many. Keep a",
        "   kit entry alongside only if the user wants it.",
        "7. Reconciliation: if the match report lists a missing part the user",
        "   believes they own under another name, treat it as a rename/merge —",
        "   move the inventory entry to the project vocabulary (or add the",
        "   specific entry) and log the old name with action \"corrected\".",
        "   When the user asks to \"reconcile\", walk the missing parts from",
        "   the match report one by one and ask which they actually own.",
        "",
        "## Photo intake — vision v1",
        "",
        "Photos are another intake source: same confirmation loop, same",
        "schema, same alias logging.",
        "",
    ]
    if photo_names:
        staged = ", ".join(f"{PHOTO_DIRNAME}/{name}" for name in photo_names)
        lines += [
            f"Staged at launch: {staged} — begin by identifying the parts in",
            "these.",
            "",
        ]
    lines += [
        f"- Photos staged at launch live in `{PHOTO_DIRNAME}/`. If the user",
        "  gives a path to an image mid-session (or drops one into this",
        "  folder), read it with your file tools — you can see images.",
        "- Identify each distinct electronic part visible and count units",
        "  where possible. Present the results as DRAFT entries in the",
        "  confirmation loop, one line per detected part:",
        "  `photos/bench.jpg → 470 ohm resistor ×25 (confidence 0.7 — blue",
        "  axial body, bands unreadable)`",
        "- Treat uncertain identifications as ambiguous entries: ask (\"about",
        "  20 axial resistors, but I can't read the bands — what value?\")",
        "  rather than writing a guess. Never write unconfirmed photo entries.",
        "- On confirmation, write them like any other entry plus provenance",
        "  fields the schema tolerates: `\"source\": \"photo\"` and",
        "  `\"confidence\"` (0.0–1.0, your identification confidence — keep it",
        "  even after the user confirms). When a photo-detected part merges",
        "  into an existing entry, just sum the quantity; don't add",
        "  provenance fields to entries the user typed.",
        "- Alias records for photo entries use your visual description as",
        "  \"raw\" and add the photo filename:",
        "",
        '  {"raw": "blue axial resistor, 4-band", "name": "470 ohm resistor", "quantity": 25, "action": "photo", "photo": "bench.jpg", "confidence": 0.7}',
        "",
    ]
    if projects_loaded:
        lines += [
            "## Project database intake — defining what to build",
            "",
            "The project database is `projects.json` in this folder (same",
            "schema the matcher reads). When the user wants to add, change, or",
            'remove a PROJECT — "add a project", "I want to build X", "put',
            'that on my build list" — edit `projects.json`:',
            "",
            '1. Schema: `{"projects": [{"name": str, "description": str,',
            '   "parts": [{"name": str, "quantity": int >= 1}, ...]}, ...]}`.',
            "   `description` is optional; `parts` must be non-empty.",
            "2. Vocabulary is the whole point of a personal database: for",
            "   parts the user owns, spell part names EXACTLY as the",
            "   inventory does — the matcher matches names exactly, and",
            "   honest BUILD NOW rows come from projects written around the",
            '   user\'s real parts (their "USB Type-B cable", not a generic',
            '   "USB cable" they don\'t own). For parts not owned yet, mint',
            "   shoppable canonical names (same rules as inventory intake).",
            "3. Draft the complete parts list from the project description —",
            "   quantities included, hookup consumables too (breadboard,",
            "   jumper wires, resistors). Ask about anything ambiguous (which",
            "   board? how many LEDs?), show the drafted project for",
            "   confirmation, then write.",
            "4. Adapting a known project to the parts on hand is a normal",
            "   move: copy it in with substitutions applied (an Arduino Uno",
            "   standing in for a Nano, the user's actual cable) and note the",
            "   substitution in the description.",
            "5. Alias logging still applies while discussing projects: if the",
            "   user refers to an owned part by another name, append a",
            '   "reference" record to `aliases.jsonl`.',
            "",
        ]
        if projects_store_name:
            lines += [
                "Changes to `projects.json` sync back to the user's",
                f"`{projects_store_name}` when the session ends (with a",
                "backup), so keep it valid JSON at all times.",
                "",
                "Starter material: the bundled sample database at",
                f"`{SAMPLE_PROJECTS_PATH}`",
                "holds ten classic beginner projects — read it when the user",
                "wants ideas to adapt to their parts.",
                "",
            ]
        else:
            lines += [
                "The loaded database is the bundled sample: edits stay in",
                "this workspace and are never written back to the sample. If",
                "the user wants a persistent personal database, suggest",
                "re-running chat with their own projects path — a path that",
                "doesn't exist yet starts an empty database and is created on",
                "first sync.",
                "",
            ]
    lines += [
        "When the session ends, PartsMatcher validates the updated",
        "`inventory.json` and syncs it — plus any new alias records — back to",
        "the user's own files, so keep both files valid at all times.",
        "",
    ]
    return "\n".join(lines)


def _resolve_workspace_dir(workdir: "Optional[str]") -> Path:
    if workdir is None:
        return Path(tempfile.mkdtemp(prefix=WORKSPACE_PREFIX))
    base = Path(workdir).expanduser().resolve()
    base.mkdir(parents=True, exist_ok=True)
    return base


def _guard_claude_md(base: Path) -> None:
    """A CLAUDE.md not generated by PartsMatcher is never overwritten — that
    would clobber a file the user owns."""
    claude_md = base / "CLAUDE.md"
    if claude_md.exists():
        existing = claude_md.read_text(encoding="utf-8")
        if CONTEXT_MARKER not in existing:
            raise PartsMatcherError(
                f"refusing to overwrite {claude_md} — it was not generated by "
                "PartsMatcher; pick a different --workdir"
            )


def prepare_workspace(
    workdir: "Optional[str]",
    context_markdown: str,
    data_files: "dict[str, str]",
) -> Path:
    """Create (or reuse) the session directory and write CLAUDE.md + data files."""
    base = _resolve_workspace_dir(workdir)
    _guard_claude_md(base)
    (base / "CLAUDE.md").write_text(context_markdown, encoding="utf-8")
    for name, text in data_files.items():
        (base / name).write_text(text, encoding="utf-8")
    return base


def stage_photos(workspace: Path, photos: "Sequence[Path]") -> "list[str]":
    """Copy photos into workspace/photos/, deduplicating clashing basenames."""
    if not photos:
        return []
    photo_dir = workspace / PHOTO_DIRNAME
    photo_dir.mkdir(exist_ok=True)
    staged = []
    for source in photos:
        candidate = photo_dir / source.name
        counter = 2
        while candidate.exists():
            candidate = photo_dir / f"{source.stem}-{counter}{source.suffix}"
            counter += 1
        shutil.copy2(source, candidate)
        staged.append(candidate.name)
    return staged


def _count_records(text: str) -> int:
    return len([line for line in text.splitlines() if line.strip()])


def _sync_inventory(
    workspace: Path,
    *,
    original_inventory_text: str,
    inventory_store: "Optional[Path]",
) -> "list[str]":
    """Flow a changed workspace inventory back to the user's own file."""
    inventory_path = workspace / "inventory.json"
    try:
        updated = inventory_path.read_text(encoding="utf-8")
    except OSError:
        return [
            f"warning: {inventory_path} is missing; your inventory file was "
            "left untouched"
        ]
    if updated == original_inventory_text:
        return []
    try:
        new_inventory = parse_inventory(json.loads(updated))
    except (json.JSONDecodeError, PartsMatcherError) as exc:
        return [
            f"warning: the session changed inventory.json but it no longer "
            f"validates ({exc}); your inventory file was left untouched — "
            f"the edited copy is at {inventory_path}"
        ]
    old_inventory = parse_inventory(json.loads(original_inventory_text))
    delta = (
        f"{old_inventory.distinct_parts} → {new_inventory.distinct_parts} part "
        f"types, {old_inventory.total_units} → {new_inventory.total_units} parts"
    )
    if inventory_store is None:
        return [
            f"inventory changed during the session ({delta}). You were using "
            f"the bundled sample, so nothing was overwritten — the updated "
            f"file is at {inventory_path}; pass your own inventory path to "
            "persist changes automatically."
        ]
    backup = inventory_store.with_name(inventory_store.name + ".bak")
    try:
        backup.write_text(
            inventory_store.read_text(encoding="utf-8"), encoding="utf-8"
        )
        inventory_store.write_text(updated, encoding="utf-8")
    except OSError as exc:
        return [
            f"warning: could not update {inventory_store} ({exc}); the edited "
            f"copy is at {inventory_path}"
        ]
    return [
        f"inventory updated: {inventory_store} ({delta}; previous version "
        f"saved to {backup.name})"
    ]


def _new_alias_records(
    workspace: Path, alias_seed_count: int
) -> "tuple[list[str], int]":
    """Valid alias lines appended past the seeded records, plus malformed count."""
    alias_path = workspace / ALIAS_FILENAME
    try:
        alias_text = alias_path.read_text(encoding="utf-8")
    except OSError:
        return [], 0
    lines = [line for line in alias_text.splitlines() if line.strip()]
    valid, skipped = [], 0
    for line in lines[alias_seed_count:]:
        try:
            record = json.loads(line)
        except json.JSONDecodeError:
            skipped += 1
            continue
        if isinstance(record, dict) and record.get("raw") and record.get("name"):
            valid.append(line)
        else:
            skipped += 1
    return valid, skipped


def _sync_projects(
    workspace: Path,
    *,
    original_projects_text: "Optional[str]",
    projects_store: "Optional[Path]",
) -> "list[str]":
    """Flow a changed workspace project database back to the user's own file.

    A ``projects_store`` that does not exist yet is created on first sync —
    that's how a brand-new personal database bootstraps from an empty one.
    """
    if original_projects_text is None:
        return []  # session had no project database loaded
    projects_path = workspace / "projects.json"
    try:
        updated = projects_path.read_text(encoding="utf-8")
    except OSError:
        return [
            f"warning: {projects_path} is missing; your project database "
            "was left untouched"
        ]
    if updated == original_projects_text:
        return []
    try:
        new_projects = parse_projects(json.loads(updated))
    except (json.JSONDecodeError, PartsMatcherError) as exc:
        return [
            f"warning: the session changed projects.json but it no longer "
            f"validates ({exc}); your project database was left untouched — "
            f"the edited copy is at {projects_path}"
        ]
    old_projects = parse_projects(json.loads(original_projects_text))
    delta = f"{len(old_projects)} → {len(new_projects)} projects"
    if projects_store is None:
        return [
            f"projects.json changed during the session ({delta}), but the "
            "loaded database was the bundled sample, so nothing was "
            f"overwritten — the edited copy is at {projects_path}; pass your "
            "own projects path to persist changes automatically."
        ]
    try:
        if projects_store.exists():
            backup = projects_store.with_name(projects_store.name + ".bak")
            backup.write_text(
                projects_store.read_text(encoding="utf-8"), encoding="utf-8"
            )
            suffix = f"; previous version saved to {backup.name}"
        else:
            suffix = "; new file"
        projects_store.write_text(updated, encoding="utf-8")
    except OSError as exc:
        return [
            f"warning: could not update {projects_store} ({exc}); the edited "
            f"copy is at {projects_path}"
        ]
    return [f"project database updated: {projects_store} ({delta}{suffix})"]


def _sync_aliases(
    workspace: Path,
    *,
    alias_seed_count: int,
    alias_store: "Optional[Path]",
) -> "list[str]":
    """Append alias records added this session to the persistent dataset."""
    alias_path = workspace / ALIAS_FILENAME
    valid, skipped = _new_alias_records(workspace, alias_seed_count)
    messages = []
    if skipped:
        messages.append(
            f"warning: skipped {skipped} malformed alias record(s) in "
            f"{alias_path.name}"
        )
    if not valid:
        return messages
    if alias_store is None:
        messages.append(
            f"{len(valid)} naming-alias record(s) captured at {alias_path} — "
            "pass your own inventory path to grow a persistent alias dataset."
        )
        return messages
    try:
        with open(alias_store, "a", encoding="utf-8") as handle:
            for line in valid:
                handle.write(line + "\n")
    except OSError as exc:
        messages.append(
            f"warning: could not append to {alias_store} ({exc}); new records "
            f"remain at {alias_path}"
        )
        return messages
    messages.append(
        f"{len(valid)} naming-alias record(s) appended to {alias_store} "
        "(dataset for the future vision module)"
    )
    return messages


def _write_session_record(
    workspace: Path,
    *,
    inventory_text: str,
    inventory_store: "Optional[Path]",
    alias_store: "Optional[Path]",
    alias_seed_count: int,
    projects_text: "Optional[str]" = None,
    projects_store: "Optional[Path]" = None,
) -> None:
    """Persist what `recover` needs to re-run the end-of-session sync."""
    record = {
        "inventory_store": None if inventory_store is None else str(inventory_store),
        "alias_store": None if alias_store is None else str(alias_store),
        "alias_seed_count": alias_seed_count,
        "original_inventory": inventory_text,
        "projects_store": None if projects_store is None else str(projects_store),
        "original_projects": projects_text,
    }
    (workspace / SESSION_FILENAME).write_text(
        json.dumps(record, indent=2), encoding="utf-8"
    )


def find_recoverable_workspaces(tmp_root: "Optional[Path]" = None) -> "list[Path]":
    """Chat workspaces in the temp directory carrying a session record,
    newest first."""
    root = _resolve_tmp_root(tmp_root)
    stamped = []
    for candidate in root.glob(WORKSPACE_PREFIX + "*"):
        try:
            mtime = (candidate / SESSION_FILENAME).stat().st_mtime
        except OSError:
            continue
        stamped.append((mtime, candidate))
    stamped.sort(key=lambda item: item[0], reverse=True)
    return [candidate for _, candidate in stamped]


def _load_session_record(workspace: Path) -> dict:
    sidecar = workspace / SESSION_FILENAME
    try:
        record = json.loads(sidecar.read_text(encoding="utf-8"))
    except OSError:
        raise PartsMatcherError(
            f"{workspace} is not a recoverable chat workspace — no "
            f"{SESSION_FILENAME} found (sessions started before v0.5.0 "
            "predate recovery support)"
        )
    except json.JSONDecodeError as exc:
        raise PartsMatcherError(f"could not parse {sidecar}: {exc}")
    if not isinstance(record, dict):
        raise PartsMatcherError(f"{sidecar} does not hold a session record")
    return record


def _record_path(record: dict, key: str) -> "Optional[Path]":
    value = record.get(key)
    return Path(value) if isinstance(value, str) and value else None


@dataclass
class WorkspaceStatus:
    """What a leftover chat workspace still holds, and whether it can go.

    Workspaces pile up in the temp directory — one per session, each with a
    full copy of the inventory. `pending` lists work that exists only inside
    this workspace; when it is empty the directory is disposable.
    """

    path: Path
    modified: float
    pending: "list[str]" = field(default_factory=list)
    error: "Optional[str]" = None

    @property
    def synced(self) -> bool:
        """True when deleting the workspace would lose nothing."""
        return self.error is None and not self.pending


def _pending_file_change(
    workspace_file: Path,
    *,
    original_text: "Optional[str]",
    store: "Optional[Path]",
    label: str,
) -> "Optional[str]":
    """Describe an edit the workspace still owes, or None if nothing is owed."""
    if original_text is None:
        return None  # the session never loaded one
    try:
        updated = workspace_file.read_text(encoding="utf-8")
    except OSError:
        return None  # nothing left in the workspace to lose
    if updated == original_text:
        return None
    if store is None:
        return (
            f"{label} edits with no destination file (sample session) — this "
            "workspace holds the only copy"
        )
    try:
        if store.read_text(encoding="utf-8") == updated:
            return None
    except OSError:
        pass
    return f"{label} edits not yet written to {store}"


def _pending_aliases(
    workspace: Path, *, alias_seed_count: int, alias_store: "Optional[Path]"
) -> "Optional[str]":
    """Describe alias records the workspace still owes the dataset."""
    valid, _ = _new_alias_records(workspace, alias_seed_count)
    if not valid:
        return None
    if alias_store is None:
        return (
            f"{len(valid)} naming-alias record(s) with no destination file "
            "(sample session) — this workspace holds the only copy"
        )
    try:
        existing = [
            line
            for line in alias_store.read_text(encoding="utf-8").splitlines()
            if line.strip()
        ]
    except OSError:
        existing = None
    if existing is not None and existing[-len(valid) :] == valid:
        return None
    return f"{len(valid)} naming-alias record(s) not yet appended to {alias_store}"


def inspect_workspace(workspace: Path) -> WorkspaceStatus:
    """Report what a chat workspace still owes, without writing anything.

    Uses the same already-in-sync tests `recover_session` runs, so a
    workspace reported synced is one `recover` would find nothing to do for.
    """
    try:
        modified = (workspace / SESSION_FILENAME).stat().st_mtime
    except OSError:
        modified = 0.0
    try:
        record = _load_session_record(workspace)
    except PartsMatcherError as exc:
        return WorkspaceStatus(path=workspace, modified=modified, error=str(exc))

    original_inventory = record.get("original_inventory")
    if not isinstance(original_inventory, str):
        original_inventory = ""
    original_projects = record.get("original_projects")
    if not isinstance(original_projects, str):
        original_projects = None
    seed_count = record.get("alias_seed_count")
    if not isinstance(seed_count, int) or seed_count < 0:
        seed_count = 0

    owed = (
        _pending_file_change(
            workspace / "inventory.json",
            original_text=original_inventory,
            store=_record_path(record, "inventory_store"),
            label="inventory",
        ),
        _pending_file_change(
            workspace / "projects.json",
            original_text=original_projects,
            store=_record_path(record, "projects_store"),
            label="project database",
        ),
        _pending_aliases(
            workspace,
            alias_seed_count=seed_count,
            alias_store=_record_path(record, "alias_store"),
        ),
    )
    return WorkspaceStatus(
        path=workspace,
        modified=modified,
        pending=[item for item in owed if item is not None],
    )


def inspect_workspaces(tmp_root: "Optional[Path]" = None) -> "list[WorkspaceStatus]":
    """Status for every recoverable workspace in the temp directory, newest first."""
    return [inspect_workspace(path) for path in find_recoverable_workspaces(tmp_root)]


def _format_age(modified: float, *, now: "Optional[float]" = None) -> str:
    """Coarse human age — enough to spot which leftovers are stale."""
    seconds = max(0.0, (time.time() if now is None else now) - modified)
    if seconds < 90:
        return "just now"
    minutes = seconds / 60
    if minutes < 90:
        return f"{int(round(minutes))}m ago"
    hours = minutes / 60
    if hours < 36:
        return f"{int(round(hours))}h ago"
    return f"{int(round(hours / 24))}d ago"


def _status_label(status: WorkspaceStatus) -> str:
    if status.error is not None:
        return "unreadable"
    return "synced" if status.synced else "unsynced"


def _print_status_detail(status: WorkspaceStatus, indent: str = "      ") -> None:
    if status.error is not None:
        print(f"{indent}{status.error}")
    for item in status.pending:
        print(f"{indent}{item}")


def _resolve_tmp_root(tmp_root: "Optional[Path]") -> Path:
    return Path(tmp_root) if tmp_root is not None else Path(tempfile.gettempdir())


def list_workspaces(tmp_root: "Optional[Path]" = None) -> int:
    """Print every recoverable chat workspace and what each still owes."""
    root = _resolve_tmp_root(tmp_root)
    statuses = inspect_workspaces(root)
    if not statuses:
        print(f"no recoverable chat workspaces under {root}")
        return 0
    print(f"{len(statuses)} recoverable chat workspace(s) under {root}:")
    for status in statuses:
        print(
            f"  {status.path}  ({_format_age(status.modified)}) — "
            f"{_status_label(status)}"
        )
        _print_status_detail(status)
    disposable = [status for status in statuses if status.synced]
    if disposable:
        print(
            f"\n`partsmatcher recover --clean` would remove {len(disposable)} "
            f"of {len(statuses)} (nothing left to sync)."
        )
    else:
        print("\nrun `partsmatcher recover PATH` to sync one back.")
    return 0


def clean_workspaces(tmp_root: "Optional[Path]" = None, *, force: bool = False) -> int:
    """Delete leftover chat workspaces that hold nothing worth keeping.

    Workspaces with unsynced changes are kept and reported unless `force` is
    set. Returns 1 if any deletion failed, 0 otherwise.
    """
    root = _resolve_tmp_root(tmp_root)
    statuses = inspect_workspaces(root)
    if not statuses:
        print(f"no recoverable chat workspaces under {root}")
        return 0

    removed, kept, failed = [], [], []
    for status in statuses:
        if not force and not status.synced:
            kept.append(status)
            continue
        try:
            shutil.rmtree(status.path)
        except OSError as exc:
            failed.append((status, exc))
            continue
        removed.append(status)

    if removed:
        unsynced = [status for status in removed if not status.synced]
        note = f" ({len(unsynced)} with unsynced changes — --force)" if unsynced else ""
        print(f"removed {len(removed)} workspace(s){note}:")
        for status in removed:
            print(f"  {status.path}  ({_format_age(status.modified)})")
    if kept:
        print(
            f"kept {len(kept)} workspace(s) still holding changes — run "
            "`partsmatcher recover PATH` on each first, or pass --force to "
            "delete them anyway:"
        )
        for status in kept:
            print(f"  {status.path}  ({_format_age(status.modified)})")
            _print_status_detail(status)
    for status, exc in failed:
        print(
            f"warning: could not remove {status.path} ({exc})",
            file=sys.stderr,
        )
    if not removed and not failed:
        print("nothing removed.")
    return 1 if failed else 0


def recover_session(
    workspace: "Optional[str]" = None, tmp_root: "Optional[Path]" = None
) -> int:
    """Re-run the end-of-session sync for a session that never exited cleanly.

    A closed terminal window or crash kills the chat before `run_chat` can
    flow the workspace's inventory edits and new alias records back to the
    user's files. Every workspace carries a session record, so the same
    validate-and-sync can run afterward. Safe to re-run: files already in
    sync are detected and left alone.
    """
    if workspace is not None:
        target = Path(workspace).expanduser()
    else:
        root = _resolve_tmp_root(tmp_root)
        candidates = find_recoverable_workspaces(root)
        if not candidates:
            raise PartsMatcherError(
                f"no recoverable chat workspaces found under {root} — pass "
                "the workspace directory explicitly if it lives elsewhere"
            )
        target = candidates[0]
        if len(candidates) > 1:
            print(
                f"({len(candidates)} recoverable workspaces found; using the "
                "newest — pass a path to pick another)"
            )
    record = _load_session_record(target)
    inventory_store = _record_path(record, "inventory_store")
    alias_store = _record_path(record, "alias_store")
    projects_store = _record_path(record, "projects_store")
    seed_count = record.get("alias_seed_count")
    if not isinstance(seed_count, int) or seed_count < 0:
        seed_count = 0
    original_inventory = record.get("original_inventory")
    if not isinstance(original_inventory, str):
        original_inventory = ""
    original_projects = record.get("original_projects")
    if not isinstance(original_projects, str):
        original_projects = None

    print(f"recovering chat session: {target}")
    messages = []

    inventory_synced = False
    if inventory_store is not None:
        try:
            store_text = inventory_store.read_text(encoding="utf-8")
            workspace_text = (target / "inventory.json").read_text(encoding="utf-8")
        except OSError:
            store_text = workspace_text = None
        if store_text is not None and store_text == workspace_text:
            if store_text != original_inventory:
                messages.append(
                    f"inventory already in sync: {inventory_store} matches "
                    "the session workspace"
                )
            inventory_synced = True
    if not inventory_synced:
        messages += _sync_inventory(
            target,
            original_inventory_text=original_inventory,
            inventory_store=inventory_store,
        )

    projects_synced = False
    if projects_store is not None:
        try:
            store_text = projects_store.read_text(encoding="utf-8")
            workspace_text = (target / "projects.json").read_text(encoding="utf-8")
        except OSError:
            store_text = workspace_text = None
        if store_text is not None and store_text == workspace_text:
            if store_text != original_projects:
                messages.append(
                    f"project database already in sync: {projects_store} "
                    "matches the session workspace"
                )
            projects_synced = True
    if not projects_synced:
        messages += _sync_projects(
            target,
            original_projects_text=original_projects,
            projects_store=projects_store,
        )

    valid, _ = _new_alias_records(target, seed_count)
    aliases_synced = False
    if valid and alias_store is not None:
        try:
            existing = [
                line
                for line in alias_store.read_text(encoding="utf-8").splitlines()
                if line.strip()
            ]
        except OSError:
            existing = None
        if existing is not None and existing[-len(valid) :] == valid:
            messages.append(
                f"{len(valid)} naming-alias record(s) already at the end of "
                f"{alias_store} — nothing new to append"
            )
            aliases_synced = True
    if not aliases_synced:
        messages += _sync_aliases(
            target, alias_seed_count=seed_count, alias_store=alias_store
        )

    if not messages:
        messages = [
            "nothing to recover — the session left no changes that need syncing"
        ]
    for message in messages:
        print(message)
    return 0


def run_chat(
    *,
    inventory: Inventory,
    inventory_text: str,
    report: "Optional[MatchReport]" = None,
    projects_text: "Optional[str]" = None,
    inventory_store: "Optional[Path]" = None,
    projects_store: "Optional[Path]" = None,
    alias_store: "Optional[Path]" = None,
    alias_seed_text: str = "",
    sync: bool = True,
    photos: "Sequence[Path]" = (),
    workdir: "Optional[str]" = None,
    prompt: "Optional[str]" = None,
    claude_bin: str = "claude",
    claude_args: "Sequence[str]" = (),
    which: "Callable[[str], Optional[str]]" = shutil.which,
    launch: "Callable[..., int]" = subprocess.call,
) -> int:
    """Prepare the workspace, hand the terminal over to Claude Code, sync back.

    `which` and `launch` are injectable so tests never need Claude installed.
    The child inherits this process's stdin/stdout/stderr, so it talks to the
    user's real terminal directly — the full interactive Claude Code UI.

    After the session ends, inventory edits made in the workspace are
    validated and written back to `inventory_store` (with a .bak backup), and
    alias records appended during the session flow into `alias_store`. With a
    `None` store (bundled sample data) nothing outside the workspace is
    touched — the summary says where the files are instead.
    """
    claude_path = find_claude(claude_bin, which=which)
    if claude_path is None:
        print(CLAUDE_NOT_FOUND_HINT.format(binary=claude_bin), file=sys.stderr)
        return 2

    workspace = _resolve_workspace_dir(workdir)
    _guard_claude_md(workspace)
    staged_photos = stage_photos(workspace, photos)
    match_command = None
    if projects_text is not None:
        # The workspace is a bare temp dir with no path back to this package,
        # so hand Claude an invocation that works from there.
        package_root = Path(__file__).resolve().parent.parent
        match_command = (
            f"PYTHONPATH={shlex.quote(str(package_root))} "
            f"{shlex.quote(sys.executable or 'python3')} -m partsmatcher "
            "match inventory.json projects.json"
        )
    context = build_context_markdown(
        inventory,
        report,
        photo_names=staged_photos,
        match_command=match_command,
        projects_loaded=projects_text is not None,
        projects_store_name=None if projects_store is None else projects_store.name,
    )
    data_files = {"inventory.json": inventory_text, ALIAS_FILENAME: alias_seed_text}
    if projects_text is not None:
        data_files["projects.json"] = projects_text
    prepare_workspace(str(workspace), context, data_files)
    _write_session_record(
        workspace,
        inventory_text=inventory_text,
        inventory_store=inventory_store,
        alias_store=alias_store,
        alias_seed_count=_count_records(alias_seed_text),
        projects_text=projects_text,
        projects_store=projects_store,
    )
    if staged_photos and not prompt:
        prompt = DEFAULT_PHOTO_PROMPT
    elif not prompt:
        prompt = DEFAULT_KICKOFF_PROMPT

    print(
        f"PartsMatcher chat — {inventory.distinct_parts} part types "
        f"({inventory.total_units} parts) loaded as context."
    )
    print(f"Session workspace: {workspace}")
    print("  CLAUDE.md — inventory + match report Claude reads at startup")
    print("  " + " / ".join(sorted(data_files)) + " — live data files")
    if staged_photos:
        print(
            f"  {PHOTO_DIRNAME}/ — {len(staged_photos)} photo(s) staged for "
            "identification"
        )
    print(
        "Describe new parts in plain language and Claude will fold them into "
        "inventory.json, logging naming aliases as it goes."
    )
    print(
        "Launching your local Claude Code (`claude`) — existing login, "
        "no API key. Type /exit to come back."
    )
    print(
        "(If the terminal dies before a clean exit, `python -m partsmatcher "
        "recover` syncs the session back afterward.)"
    )
    print()

    command = [claude_path, *claude_args]
    if prompt:
        command.append(prompt)
    try:
        code = launch(command, cwd=str(workspace))
    except KeyboardInterrupt:
        code = 130

    if sync:
        messages = _sync_inventory(
            workspace,
            original_inventory_text=inventory_text,
            inventory_store=inventory_store,
        )
        messages += _sync_projects(
            workspace,
            original_projects_text=projects_text,
            projects_store=projects_store,
        )
        messages += _sync_aliases(
            workspace,
            alias_seed_count=_count_records(alias_seed_text),
            alias_store=alias_store,
        )
        for message in messages:
            print(message)
    else:
        print(f"(--no-sync: any changes stay in the workspace at {workspace})")
    return code
