"""Command-line interface for PartsMatcher.

Two subcommands share one inventory as the source of truth:

- ``match`` — the deterministic set-cover report (offline, zero dependencies)
- ``chat`` — hands the same inventory to the user's locally installed Claude
  Code CLI for improvised project ideas (see ``partsmatcher/chat.py``)
- ``app`` — the local app: the same session served as a browser page with
  chat embedded (see ``partsmatcher/app/``)

For backwards compatibility, ``partsmatcher [INVENTORY] [PROJECTS] [flags]``
without a subcommand behaves as ``partsmatcher match ...``.
"""

from __future__ import annotations

import argparse
import json
import os
import sys
from pathlib import Path

from . import __version__
from .matcher import (
    DEFAULT_ALMOST_THRESHOLD,
    Inventory,
    MatchReport,
    PartsMatcherError,
    ProjectMatch,
    match,
    parse_inventory,
    parse_projects,
)

SAMPLE_DIR = Path(__file__).resolve().parent / "samples"
SAMPLE_INVENTORY = SAMPLE_DIR / "inventory.json"
SAMPLE_PROJECTS = SAMPLE_DIR / "projects.json"

KNOWN_COMMANDS = ("match", "chat", "app", "recover")
_TOP_LEVEL_FLAGS = ("-h", "--help", "--version")


def _add_input_arguments(parser: argparse.ArgumentParser) -> None:
    parser.add_argument(
        "inventory",
        nargs="?",
        metavar="INVENTORY_JSON",
        help="parts you own (default: bundled sample inventory)",
    )
    parser.add_argument(
        "projects",
        nargs="?",
        metavar="PROJECTS_JSON",
        help="project database (default: bundled sample projects)",
    )
    parser.add_argument(
        "--almost",
        type=int,
        default=DEFAULT_ALMOST_THRESHOLD,
        metavar="N",
        help=(
            "max total missing parts (in units, summed over part types) for "
            "the ALMOST THERE group (default: %(default)s)"
        ),
    )


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog="partsmatcher",
        description=(
            "Match the parts you own against a project database — a fast "
            "deterministic report, plus a conversational mode that hands your "
            "inventory to your local Claude Code."
        ),
        epilog=(
            "Run without a subcommand for `match`. With no file arguments the "
            "bundled sample data is used, so `python -m partsmatcher` runs "
            "out of the box."
        ),
    )
    parser.add_argument(
        "--version", action="version", version=f"%(prog)s {__version__}"
    )
    subparsers = parser.add_subparsers(dest="command", required=True)

    match_parser = subparsers.add_parser(
        "match",
        help="deterministic report: BUILD NOW / ALMOST THERE / NOT YET",
        description=(
            "Group projects into BUILD NOW / ALMOST THERE / NOT YET against "
            "your inventory. Fully offline; never needs Claude installed."
        ),
    )
    _add_input_arguments(match_parser)
    match_parser.add_argument(
        "--json",
        action="store_true",
        dest="as_json",
        help="emit the report as JSON on stdout",
    )
    match_parser.add_argument(
        "-v",
        "--verbose",
        action="store_true",
        help="also list exactly what each NOT YET project is missing",
    )
    match_parser.add_argument(
        "--no-color",
        action="store_true",
        help="disable ANSI colors (the NO_COLOR env var is honored too)",
    )

    chat_parser = subparsers.add_parser(
        "chat",
        help="chat with your local Claude Code about what to build",
        description=(
            "Launch your locally installed Claude Code CLI (`claude`) with "
            "the inventory injected as session context — improvised project "
            "ideas, wiring help, and substitutions grounded in exactly what "
            "you own. Uses your existing Claude login; no API key. Pass extra "
            "arguments through to claude after `--`."
        ),
    )
    _add_input_arguments(chat_parser)
    chat_parser.add_argument(
        "--no-projects",
        action="store_true",
        help="skip the project database; give Claude only the inventory",
    )
    chat_parser.add_argument(
        "--workdir",
        metavar="DIR",
        help=(
            "session workspace directory (default: a fresh temp directory); "
            "an existing CLAUDE.md not generated by PartsMatcher is never "
            "overwritten"
        ),
    )
    chat_parser.add_argument(
        "--photo",
        action="append",
        metavar="IMAGE",
        help=(
            "stage a photo of parts for identification (repeatable); the "
            "session starts by identifying them into draft inventory entries"
        ),
    )
    chat_parser.add_argument(
        "--prompt",
        metavar="TEXT",
        help="opening prompt to hand Claude once the session starts",
    )
    chat_parser.add_argument(
        "--claude-bin",
        default="claude",
        metavar="PATH",
        help="Claude Code binary to launch (default: %(default)s)",
    )
    chat_parser.add_argument(
        "--no-sync",
        action="store_true",
        help=(
            "after the session, leave inventory edits and new alias records "
            "in the workspace instead of syncing them back to your files"
        ),
    )

    app_parser = subparsers.add_parser(
        "app",
        help="local app: chat with Claude in your browser, embedded views",
        description=(
            "Serve the PartsMatcher app on localhost: chat with your local "
            "Claude Code in the browser (headless `claude -p` per turn — "
            "existing login, no API key) beside a live inventory and match "
            "report. Same workspace mechanics as `chat`: generated CLAUDE.md "
            "context, sync-back with backups, alias logging, `recover`."
        ),
    )
    _add_input_arguments(app_parser)
    app_parser.add_argument(
        "--no-projects",
        action="store_true",
        help="skip the project database; give Claude only the inventory",
    )
    app_parser.add_argument(
        "--workdir",
        metavar="DIR",
        help=(
            "session workspace directory (default: a fresh temp directory); "
            "an existing CLAUDE.md not generated by PartsMatcher is never "
            "overwritten"
        ),
    )
    app_parser.add_argument(
        "--photo",
        action="append",
        metavar="IMAGE",
        help=(
            "stage a photo of parts for identification (repeatable); the "
            "session starts by identifying them into draft inventory entries"
        ),
    )
    app_parser.add_argument(
        "--prompt",
        metavar="TEXT",
        help="opening prompt for the session's kickoff turn",
    )
    app_parser.add_argument(
        "--claude-bin",
        default="claude",
        metavar="PATH",
        help="Claude Code binary to drive (default: %(default)s)",
    )
    app_parser.add_argument(
        "--port",
        type=int,
        default=0,
        metavar="N",
        help="port to serve on (default: an OS-assigned free port)",
    )
    app_parser.add_argument(
        "--no-browser",
        action="store_true",
        help="don't open the browser automatically; just print the URL",
    )
    app_parser.add_argument(
        "--no-sync",
        action="store_true",
        help=(
            "after the session, leave inventory edits and new alias records "
            "in the workspace instead of syncing them back to your files"
        ),
    )

    recover_parser = subparsers.add_parser(
        "recover",
        help="sync back a chat session that ended without a clean exit",
        description=(
            "Re-run the end-of-session sync for a chat workspace whose "
            "session died before it could flow inventory edits and new "
            "alias records back to your files (closed terminal, crash). "
            "Same validation and .bak backup as the normal exit; safe to "
            "re-run — files already in sync are left alone. --list surveys "
            "the leftover workspaces piling up in the temp directory and "
            "--clean deletes the ones with nothing left to sync."
        ),
    )
    recover_parser.add_argument(
        "workspace",
        nargs="?",
        metavar="WORKSPACE_DIR",
        help=(
            "chat workspace directory to sync back (default: the newest "
            "recoverable workspace in the system temp directory)"
        ),
    )
    recover_mode = recover_parser.add_mutually_exclusive_group()
    recover_mode.add_argument(
        "--list",
        dest="list_workspaces",
        action="store_true",
        help=(
            "list every recoverable workspace, its age, and what each still "
            "owes your files — then exit without syncing anything"
        ),
    )
    recover_mode.add_argument(
        "--clean",
        action="store_true",
        help=(
            "delete leftover workspaces whose changes are already synced "
            "back; ones still holding changes are kept and reported"
        ),
    )
    recover_parser.add_argument(
        "--force",
        action="store_true",
        help="with --clean, delete workspaces holding unsynced changes too",
    )
    return parser


def _load_json(path: Path, what: str) -> object:
    try:
        with open(path, "r", encoding="utf-8") as handle:
            return json.load(handle)
    except OSError as exc:
        reason = exc.strerror or str(exc)
        raise PartsMatcherError(f"could not read {what} file {str(path)!r}: {reason}")
    except json.JSONDecodeError as exc:
        raise PartsMatcherError(f"{what} file {str(path)!r} is not valid JSON: {exc}")


def _resolve_input_path(
    given: "str | None", sample: Path, what: str
) -> Path:
    if given is not None:
        return Path(given)
    print(
        f"note: no {what} file given, using bundled sample: {sample}",
        file=sys.stderr,
    )
    return sample


def _want_color(no_color_flag: bool) -> bool:
    if no_color_flag or "NO_COLOR" in os.environ:
        return False
    return bool(getattr(sys.stdout, "isatty", lambda: False)())


def _make_painter(enabled: bool):
    def paint(text: str, code: str) -> str:
        return f"\x1b[{code}m{text}\x1b[0m" if enabled else text

    return paint


def _pick_marks(stream) -> "tuple[str, str, str]":
    marks = ("✔", "≈", "✘")  # ✔ ≈ ✘
    encoding = getattr(stream, "encoding", None) or "ascii"
    try:
        "".join(marks).encode(encoding)
    except (UnicodeEncodeError, LookupError):
        return ("[OK]", "[~]", "[X]")
    return marks


def _n(count: int, word: str) -> str:
    return f"{count} {word}{'' if count == 1 else 's'}"


def _report_to_dict(report: MatchReport, inventory: Inventory) -> dict:
    total = len(report.build_now) + len(report.almost) + len(report.not_yet)
    return {
        "summary": {
            "projects": total,
            "build_now": len(report.build_now),
            "almost": len(report.almost),
            "not_yet": len(report.not_yet),
            "almost_threshold": report.almost_threshold,
            "inventory_part_types": inventory.distinct_parts,
            "inventory_total_parts": inventory.total_units,
        },
        "build_now": [result.to_dict() for result in report.build_now],
        "almost": [result.to_dict() for result in report.almost],
        "not_yet": [result.to_dict() for result in report.not_yet],
    }


def _print_missing_lines(result: ProjectMatch) -> None:
    for part in result.missing:
        print(
            f"      needs {part.name}: have {part.have} of {part.required} "
            f"(short {part.missing})"
        )


def _print_human(
    report: MatchReport, inventory: Inventory, *, verbose: bool, color: bool
) -> None:
    paint = _make_painter(color)
    ok_mark, near_mark, far_mark = _pick_marks(sys.stdout)
    total = len(report.build_now) + len(report.almost) + len(report.not_yet)
    print(
        f"Matched {_n(total, 'project')} against "
        f"{_n(inventory.distinct_parts, 'part type')} "
        f"({_n(inventory.total_units, 'part')} on hand)."
    )

    print()
    print(paint(f"BUILD NOW ({len(report.build_now)})", "1;32"))
    if not report.build_now:
        print("  (none)")
    for result in report.build_now:
        suffix = f" — {result.description}" if result.description else ""
        print(f"  {paint(ok_mark, '32')} {result.name}{suffix}")

    print()
    print(
        paint(f"ALMOST THERE ({len(report.almost)})", "1;33")
        + f" — short at most {_n(report.almost_threshold, 'part')}, fewest missing first"
    )
    if not report.almost:
        print("  (none)")
    for result in report.almost:
        print(
            f"  {paint(near_mark, '33')} {result.name} — "
            f"short {_n(result.total_missing, 'part')}"
        )
        if result.description:
            print(f"      {result.description}")
        _print_missing_lines(result)

    print()
    print(paint(f"NOT YET ({len(report.not_yet)})", "1;31"))
    if not report.not_yet:
        print("  (none)")
    for result in report.not_yet:
        print(
            f"  {paint(far_mark, '31')} {result.name} — "
            f"short {_n(result.total_missing, 'part')} across "
            f"{_n(result.missing_kinds, 'part type')}"
        )
        if result.description:
            print(f"      {result.description}")
        if verbose:
            _print_missing_lines(result)

    if report.not_yet and not verbose:
        print()
        print(paint("(re-run with --verbose to see what NOT YET projects need)", "2"))


def _run_match(args: argparse.Namespace) -> int:
    inventory_path = _resolve_input_path(args.inventory, SAMPLE_INVENTORY, "inventory")
    projects_path = _resolve_input_path(args.projects, SAMPLE_PROJECTS, "projects")
    try:
        inventory = parse_inventory(_load_json(inventory_path, "inventory"))
        projects = parse_projects(_load_json(projects_path, "project database"))
    except PartsMatcherError as exc:
        print(f"partsmatcher: error: {exc}", file=sys.stderr)
        return 2

    report = match(inventory, projects, almost_threshold=args.almost)

    if args.as_json:
        print(json.dumps(_report_to_dict(report, inventory), indent=2))
    else:
        _print_human(
            report, inventory, verbose=args.verbose, color=_want_color(args.no_color)
        )
    return 0


def _gather_session_inputs(args: argparse.Namespace) -> dict:
    """Load inventory/projects/photos and resolve the persistent stores —
    shared by the `chat` and `app` subcommands, which prepare identical
    workspaces. Raises PartsMatcherError on bad input."""
    from . import chat  # imported lazily: `match` never touches chat machinery

    inventory_is_sample = args.inventory is None
    projects_is_sample = args.projects is None
    inventory_path = _resolve_input_path(args.inventory, SAMPLE_INVENTORY, "inventory")
    report = None
    projects_text = None
    projects_store = None

    photos = []
    for raw in args.photo or []:
        photo = Path(raw).expanduser()
        if not photo.is_file():
            raise PartsMatcherError(f"photo not found: {raw}")
        if photo.suffix.lower() not in chat.IMAGE_SUFFIXES:
            supported = ", ".join(chat.IMAGE_SUFFIXES)
            raise PartsMatcherError(
                f"unsupported photo type {photo.suffix!r} for {raw} "
                f"(supported: {supported})"
            )
        photos.append(photo)

    inventory = parse_inventory(_load_json(inventory_path, "inventory"))
    inventory_text = inventory_path.read_text(encoding="utf-8")
    if not args.no_projects:
        projects_path = _resolve_input_path(
            args.projects, SAMPLE_PROJECTS, "projects"
        )
        if not projects_is_sample:
            projects_store = projects_path
        if projects_store is not None and not projects_path.exists():
            # A personal project database that doesn't exist yet starts
            # empty; the exit sync creates the file once it has projects.
            projects_text = '{\n  "projects": []\n}\n'
            projects = parse_projects(json.loads(projects_text))
            print(
                f"note: {projects_path} does not exist yet — starting an "
                "empty project database; it will be created when the "
                "session adds projects",
                file=sys.stderr,
            )
        else:
            projects = parse_projects(
                _load_json(projects_path, "project database")
            )
            projects_text = projects_path.read_text(encoding="utf-8")
        report = match(inventory, projects, almost_threshold=args.almost)

    # The bundled sample never gets written back to — intake results stay
    # in the workspace, and the post-session summary says where.
    inventory_store = None
    alias_store = None
    alias_seed_text = ""
    if not inventory_is_sample:
        inventory_store = inventory_path
        alias_store = inventory_path.with_name(
            inventory_path.stem + ".aliases.jsonl"
        )
        if alias_store.exists():
            alias_seed_text = alias_store.read_text(encoding="utf-8")

    return {
        "inventory": inventory,
        "inventory_text": inventory_text,
        "report": report,
        "projects_text": projects_text,
        "inventory_store": inventory_store,
        "projects_store": projects_store,
        "alias_store": alias_store,
        "alias_seed_text": alias_seed_text,
        "sync": not args.no_sync,
        "photos": photos,
        "workdir": args.workdir,
        "prompt": args.prompt,
        "claude_bin": args.claude_bin,
    }


def _run_chat(args: argparse.Namespace, claude_args: "list[str]") -> int:
    from . import chat  # imported lazily: `match` never touches chat machinery

    try:
        inputs = _gather_session_inputs(args)
        result = chat.run_chat(claude_args=claude_args, **inputs)
    except PartsMatcherError as exc:
        print(f"partsmatcher: error: {exc}", file=sys.stderr)
        return 2
    return result


def _run_app(args: argparse.Namespace) -> int:
    from . import app  # imported lazily, like chat

    try:
        inputs = _gather_session_inputs(args)
        result = app.run_app(
            almost_threshold=args.almost,
            port=args.port,
            open_browser=not args.no_browser,
            **inputs,
        )
    except PartsMatcherError as exc:
        print(f"partsmatcher: error: {exc}", file=sys.stderr)
        return 2
    return result


def _run_recover(args: argparse.Namespace) -> int:
    from . import chat  # imported lazily: `match` never touches chat machinery

    try:
        if args.force and not args.clean:
            raise PartsMatcherError("--force only applies to --clean")
        if args.list_workspaces or args.clean:
            if args.workspace is not None:
                raise PartsMatcherError(
                    "--list and --clean survey the whole temp directory — "
                    "drop the workspace path"
                )
            if args.clean:
                return chat.clean_workspaces(force=args.force)
            return chat.list_workspaces()
        return chat.recover_session(args.workspace)
    except PartsMatcherError as exc:
        print(f"partsmatcher: error: {exc}", file=sys.stderr)
        return 2


def main(argv: "list[str] | None" = None) -> int:
    argv = list(sys.argv[1:] if argv is None else argv)

    claude_args: "list[str]" = []
    if "--" in argv:
        split = argv.index("--")
        argv, claude_args = argv[:split], argv[split + 1 :]

    # Backwards compatibility: `partsmatcher inv.json proj.json --json`
    # (no subcommand) behaves as `partsmatcher match ...`.
    if not argv or (argv[0] not in KNOWN_COMMANDS and argv[0] not in _TOP_LEVEL_FLAGS):
        argv = ["match", *argv]

    parser = build_parser()
    args = parser.parse_args(argv)
    if getattr(args, "almost", 0) < 0:
        parser.error("--almost must be >= 0")

    if args.command == "chat":
        return _run_chat(args, claude_args)
    if claude_args:
        parser.error("arguments after '--' are only used by `partsmatcher chat`")
    if args.command == "app":
        return _run_app(args)
    if args.command == "recover":
        return _run_recover(args)
    return _run_match(args)


if __name__ == "__main__":
    sys.exit(main())
